[[ra_introduction_section]]
== Introduction

The AR for Enterprise Alliance Research Agenda is described in this document.

Here provide a sentence about each section.

# Other Research Agendas

## European Union
This report, entitled https://www.standict.eu/sites/default/files/2021-02/McKinsey%20report.pdf[Shaping the Digital Transformation in Europe] (published Sept 2020, prepared by McKinsey & Company), outlines nine actions that set a high bar and that directly address the four objectives for Europe’s digital transformation.

## Grand Challenges
In Mark Billinghursts' March 2021 article in Frontiers for VR, "Grand Challenges for Augmented Reality" https://www.frontiersin.org/articles/10.3389/frvir.2021.578080/full The DOI is https://doi.org/10.3389/frvir.2021.578080

He identifies the following areas as having high need for deeper research:

. Fundamental Display Technology
. Human, Information and Machine Interactions
. Tracking Technologies
. Perception and Neuroscience of AR
. Using AR for Collaboration
. Social and Ethical Aspects of AR Adoption.

Billinghurst concludes that in order to reach its full potential as a transformative technology, the above areas will need to receive far greater resources and attention.

## Future Today Institute
The Future Today Institute publishes an annual analysis. The full
https://www.dropbox.com/s/fm5c9mlmnwy9kgd/FTI_2021_Tech_Trends_Volume_All.pdf?dl=0[2021 Technology Trends Report] includes "books" focusing in different domains. One of the domains is called "New Realities" and the topics in https://www.dropbox.com/s/3esdwureqa5458f/FTI_2021_Tech_Trends_Volume_3_NewRealities_SynthMedia.pdf?dl=0[this book] and the domain of include the use of AR in enterprise

# Research Quality
An important aspect to consider in the planning and execution of any research is quality of the research and results. One of the most widely-accepted methods of ensuring that research meets or exceeds the quality threshold for a community or industry is peer review. The careful and critical review of submissions by a panel of peers ensures that, prior to public release, publications and conference papers reflect the latest research methods and that the results are sound.

All the articles included in the FindAR data set and used in quantitative analyses for this research agenda have been peer reviewed and meet the industry standard for quality.

As the field of Augmented Reality is quickly evolving, it is important for all of those intending or performing research on AR topics to contribute to development of new research methods and/or to follow the latest best practices. One source of peer-reviewed articles for methods is the https://www.igi-global.com/book/handbook-research-software-quality-innovation/259901[Handbook of Research on Software Quality Innovation in Interactive Systems] (published by IGI Global in March 2021).

# Outreach/publications
Once a research program is productive and reliable (reproducible) results are available, these need to be made available to a wide range of industry stakeholders who can deliver AR experiences that meet and exceed the requirements of end users. 
