[[ra_usage_section]]
=== How To Use This Resource

The AREA Research Agenda 2021 is published in order for researchers and research funding organizations to:

. Focus their future efforts on the topics most likely to result in rapid technology transfers from research to high impact commercial or community-based solutions serving their target audiences and/or
. Contribute directly and indirectly to one or more overarching multi-project visions and/or research roadmaps.

Those new to this Research Agenda should begin by understanding the background and context and then examining the research topic  titles. This is best achieved through the interactive dashboard published on the AREA web site. The topics can be sorted by category assignment and keyword and results are returned in the order of their computed similarity score.

Once viewing a research topic description, the user can follow links embedded in the text to other topics in this Research Agenda.

Although nothing prevents it, this resource is not designed to be read from start to finish. The core of the AREA Research Agenda, and where the user will dedicate most of their attention, is the topics which can be explored using an interactive dashboard.

The topics proposed are intended to serve as suggestions. None of the topics are mutually exclusive or entirely comprehensive. There is overlap among the themes in the topics. Researchers and research funding organizations are expected to adapt and extend or narrow the focus of their efforts using these topics only as inspiration and points of departure.

The Research Agenda does not provide implementation details or business scenarios which could emerge as a result of a group pursuing any topic. It is assumed that a wide range of organizations could be involved in proposed research topics and, subsequently, could roll out and offer value to enterprise AR ecosystem segments, based on the results of investigations in response to the recommended research topics.

While the AREA Research Committee may explore topics identified in this Research Agenda as part of its future activities and projects, the AREA Research Agenda topics are larger in scale and more complex in scope than the AREA's limited research budget can address. In addition, most of the research topics described could uncover new business opportunities which the AREA (the organization itself) is unable to bring to fruition.
