[[ra-other-research-agendas-section]]
=== Other Research Agendas
NOTE: Needs to be cleaned up. Bill will help to make the sources cited in this section be formatted with BibTec widget/plugin (we agreed to keep the source citations with the section, not have the in an annex at the end)

Research agendas differ widely in their methodologies, target audiences, scope, depth and the length of time they seek to address or influence.

This section compiles research agendas, related tools and resources identified in the preparation of this resource. They are included to offer perspectives and insights for those developing policies which will impact AR and funding AR research.

2021 April: Ecorys partnered with the XR Association and released the https://xreuropepotential.com/assets/pdf/ecorys-xr-2021-report.pdf[XR in Europe 2021 Report] which includes an assessment of XR developments by region of Europe. It also highlights gaps and areas in need of greater investment.

2019 or 2020 Oct: XR 4ALL Research Agenda - request link from Oliver Schreer (Fraunhofer Institute, HHI)

2018 Dec: https://uwe-repository.worktribe.com/OutputFile/1493581[Research Agenda for VR and AR in UK AEC industry] University of West England, Bristol

2018 Sept:	https://ec.europa.eu/growth/tools-databases/dem/monitor/content/augmented-and-virtual-reality[Augmented and Virtual Reality in Operations] Report by Capgemini Research Institute (www.capgemini.com)

2017 Oct: 	https://ec.europa.eu/growth/tools-databases/dem/monitor/content/augmented-and-virtual-reality[Digital Transformation Monitor: Augmented and Virtual Reality] Report prepared by the consortium composed of PwC, CARSA, IDATE and ESN under the 		contract Digital Entrepreneurship Monitor (EASME/COSME/2014/004)

2017 May:	https://ec.europa.eu/futurium/en/system/files/ged/vr_ecosystem_eu_report_0.pdf[Virtual reality and its potential for Europe] ECORYS report

=== European Union
This report, entitled https://www.standict.eu/sites/default/files/2021-02/McKinsey%20report.pdf[Shaping the Digital Transformation in Europe] (published Sept 2020, prepared by McKinsey & Company), outlines nine actions that set a high bar and that directly address the four objectives for Europe’s digital transformation.

=== Grand Challenges
In Mark Billinghursts' March 2021 article in Frontiers for VR, "Grand Challenges for Augmented Reality" https://www.frontiersin.org/articles/10.3389/frvir.2021.578080/full The DOI is https://doi.org/10.3389/frvir.2021.578080

He identifies the following areas as having high need for deeper research:

. Fundamental Display Technology
. Human, Information and Machine Interactions
. Tracking Technologies
. Perception and Neuroscience of AR
. Using AR for Collaboration
. Social and Ethical Aspects of AR Adoption.

Billinghurst concludes that in order to reach its full potential as a transformative technology, the above areas will need to receive far greater resources and attention.

=== Future Today Institute
The Future Today Institute publishes an annual analysis. The full
https://www.dropbox.com/s/fm5c9mlmnwy9kgd/FTI_2021_Tech_Trends_Volume_All.pdf?dl=0[2021 Technology Trends Report] includes "books" focusing in different domains. One of the domains is called "New Realities" and the topics in https://www.dropbox.com/s/3esdwureqa5458f/FTI_2021_Tech_Trends_Volume_3_NewRealities_SynthMedia.pdf?dl=0[this book] and the domain of include the use of AR in enterprise
