[[ra_scope_section]]
== Scope

The AREA Research Agenda is the focus of this resource. To provide context to the user, section 1.3 offers other research agendas that may be of interest to the same target audiences.

The AREA Research Agenda focuses on challenges that, when addressed in scalable and efficient ways meeting the needs of enterprise customers, will reduce the obstacles to widespread Enterprise Augmented Reality adoption. Enterprise customers are defined as businesses or governmental agencies whose purpose is to design, build and distribute goods and services to their customers. As a general rule, the more complex the product and/or the processes for designing and building it, the higher the potential for AR to improve efficiencies and operational processes. In parallel, the lower the industry, business or agency's tolerance for risk, the higher the potential for AR to increase safety and compliance with policies.

While some topics in this resource could also be implemented using Virtual Reality, people interacting with one or more elements of the physical world are at the center of all the topics proposed.

Some topics proposed in this research agenda could also yield technologies that will be highly valuable to individual or non-commercial users without the constraints or the support enterprise IT resources.
